sudo: false
before_script:
  - composer self
  - composer --version
  - composer install -n
before_install:
  - mysql -e 'CREATE DATABASE glpdo2_test;'
language: php
php:
  - '7.2'
  - '7.3'
services:
  - mysql
env:
  - MYSQLHOST="127.0.0.1"
  - MYSQLDB="glpdo2_test"
  - MYSQLUSER="travis"
  - MYSQLPASS=
script:
  - composer phpcs
  - composer phpstan
  - composer test -- --coverage-clover=coverage.xml
after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
    - master
    - develop

# You can delete the cache using travis-ci web interface
cache:
  directories:
    - $HOME/.composer/cache
